name: Check Winning
on:
  schedule:
    - cron: 30 13 * * 6 # every Saturday on 10:30 PM (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Check Winning 2
    steps:  

      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Run Scripts
        run: make check
        env:
          USERNAME: ${{ secrets.USERNAME2 }}
          PASSWORD: ${{ secrets.PASSWORD2 }}
          COUNT: ${{ secrets.COUNT }}
          BUYOPTION: ${{ secrets.BUYOPTION }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL:  ${{ secrets.DISCORD_WEBHOOK_URL }}
